package com.metafour.multitenancy.demo.caching;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring boot application entry point. Auto generated by Spring starter.
 * 
 * @author Imtiaz Rahi
 * @since 2017-08-25
 */
@SpringBootApplication(scanBasePackages = { "com.metafour.multitenancy.demo.caching", "com.metafour.multitenancy.config" })
public class MutitenantDemoCachingApplication {

	public static void main(String[] args) {
		SpringApplication.run(MutitenantDemoCachingApplication.class, args);
	}
}
