package com.metafour.multitenancy;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring boot application entry point. Auto generated by Spring starter.
 * 
 * @author Imtiaz Rahi
 * @since 2017-08-25
 */
@SpringBootApplication
public class MutitenantDemoAppImtiazApplication {

	public static void main(String[] args) {
		SpringApplication.run(MutitenantDemoAppImtiazApplication.class, args);
	}
}
